### ISSUE TITLE
first call works fine - but stays cached?!?

### ISSUE THREAD

**Issue by ninjamoba** [okhiroyuki/node-red-contrib-nlp#104]
When using your node-red plugin Im experiencing sucess in training the bot and useing your sample flow - however additional utterances after the first appear to only repeat the first utterance and not acknowledge a new input into the NLP.  im not sure why the intial utternace appears cached - can you confirm or disconfirm? See below debug output from node red: 

3/4/2021, 4:44:39 PMnode: outofnlp
msg.payload : Object
{ locale: "en", utterance: "who are you", settings: undefined, languageGuessed: false, localeIso2: "en" … }
3/4/2021, 4:44:45 PMnode: First Inputmsg.payload : string[5]
"hello"
3/4/2021, 4:44:45 PMnode: outofnlpmsg.payload : Object
{ locale: "en", utterance: "hello", settings: undefined, languageGuessed: false, localeIso2: "en" … }
3/4/2021, 4:44:45 PMnode: First Inputmsg.payload : string[10]
"Greetings!"
3/4/2021, 4:44:50 PMnode: Second Inputmsg.payload : string[19]
"where are you from?"
3/4/2021, 4:44:50 PMnode: outofnlpmsg.payload : Object
{ locale: "en", utterance: "hello", settings: undefined, languageGuessed: false, localeIso2: "en" … }
3/4/2021, 4:44:50 PMnode: First Inputmsg.payload : string[10]
"Hey there!"

This is more apparent from a dialog snip:
[Connected]

bryan: you dawg

bot: Hey there!

bryan: Where do you come from?

bot: Greetings!

**Comment by ninjamoba** [comment]
In the plugin I think the issue might be with the first check of the utterance to be empty
if(!hasString(node.utterance)){

But then it isnt empty anymore....

Perhaps the function should be:

node.on("input", function(msg) {
            if(!hasString(node.utterance)){
                if(hasString(msg.payload)){
                    node.utterance = msg.payload;
                }else{
                    node.warn(RED._("nlp.warn.noUtterance"));
                    return;
                }
            }
            run(node, msg);
var node.utterance = null;
        });

**Comment by okhiroyuki** [comment]
@ninjamoba Thank you for your feedback.
The problem of locked speech by msg.payload has been recognized here as well.
It will be fixed and updated.

**Comment by okhiroyuki** [comment]
@ninjamoba release v2.0.3
please check.

**Comment by ninjamoba** [comment]
This is now working for me... Thanks!

By the way... was the initialiżation of training logic handled the same way... in other words ...will a new corpus be recogniżed after the  first is trained? 

and an unrelated question... do you have plans or a roadmap to address other features of the NLP.js library via your work here on this repository? The QnA capabilities are especially interesting of NLP.js for applications in Node-red for instance.

**Comment by okhiroyuki** [comment]
>By the way... was the initialiżation of training logic handled the same way... in other words ...will a new corpus be recogniżed after the first is trained?

The training logic has not been changed.
The new corpus will be recognized after it has been trained first.

>and an unrelated question... do you have plans or a roadmap to address other features of the NLP.js library via your work here on this repository? The QnA capabilities are especially interesting of NLP.js for applications in Node-red for instance.

In particular, there are no milestones. If you have any thoughts or ideas, please feel free to discuss them below.
https://github.com/okhiroyuki/node-red-contrib-nlp/discussions
