### ISSUE TITLE
node-red node repository?

### ISSUE THREAD

**Issue by ninjamoba** [okhiroyuki/node-red-contrib-nlp#97]
Guys have you populated to the node-red (preferably) repository for us newbs struggling to install on our pallette? or perhaps a how to install note?

---my bad found it on NPM

**Comment by okhiroyuki** [comment]
Hi, @ninjamoba 

As you mentioned, this node is not registered with npm.
I'm not sure if I'll be able to do the ongoing maintenance itself properly.
I'll look into it.

**Comment by okhiroyuki** [comment]
@ninjamoba 
please check https://www.npmjs.com/package/node-red-contrib-nlp

**Comment by ninjamoba** [comment]
Thanks very much
